#!/bin/sh
#
# Launcher script for a nasqueron/rabbitmq Docker container
#
# Usage: ./run-mq blue-rabbit
# This will create a RabbitMQ container, and a rabbit@blue-rabbit cluster.

if [ $# -eq 1 ]; then
	NAME=$1
else
	echo "Usage: $0 <name to give to the container>";
	exit 1
fi

PORTS="-p 5672:5672 -p 25672:25672 -p 1883:1883 -p 8883:8883 -p 15672:15672 -p 15674:15674 -p 61613:61613 -p 4369:4369"
VOLUMES="-v /data/$NAME/log:/data/log -v /data/$NAME/mnesia:/data/mnesia"

docker run -dt $PORTS $VOLUMES --hostname $NAME --name $NAME nasqueron/rabbitmq
